# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72a7ea7e7429c5090be6d4a219c9122cb6f6ff381f07129f4ba1374b469a2960e3fefe5e55ec2614819b8e3f8bf2310abf8e948b1cb9f148d64acd1c9f0a41e8

test:
  secret_key_base: cc62756488a5928a2ab4c7f14bccfcd72666fb20c63b54bf7dcda58ceb1fef518659cb1c0ff57ee8bdbb73b7f226d622f5e2e516f9caa99c4a4cdc0e30b1026f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
